const texts = {
  ru: {
    greeting:
      "👋 Здравствуйте!\nЧерез эту платформу вы можете записаться на встречу с заключёнными в тюрьме.",
    process_canceled: "❌ Процесс отменён.",
    error_occurred: "❌ Произошла ошибка.",
    main_menu: "Основное меню:",
    already_in_process:
      "❌ Вы уже в процессе. Пожалуйста, завершите текущий процесс или используйте /cancel.",
    approved_status: `🎉 Заявка одобрена. №: {id}\n👤 Заявитель: {name}`,
    pending_status: `📊 Ваша очередь: {pos}`,
    queue_not_found: "❌ Очередь не найдена.",
    no_pending_application: "❌ У вас нет активной заявки.",
    approved_details: `🎉 Заявка одобрена. №: {id}\n👤 Заявитель: {name}\n📅 Дата подачи: {created}\n⌚️ Дата посещения: {visit}\n🏛️ Колония: {colony}\n🟢 Статус: Утверждено`,
    status_unknown: "❌ Статус заявки неизвестен.",
    no_booking_found: "❌ Заявка не найдена.",
    group_join_prompt: "🫂 Нажмите кнопку:",
    group_join_button: "📌 Перейти в группу",
    no_active_application: "❌ У вас нет активной заявки.",
    coordinates_not_found: "❌ Координаты колонии не найдены.",
    colony_location: "🏛 Локация колонии {colony}",
    cancel_confirm: "❓ Вы уверены, что хотите отменить заявку?",
    cancel_no: "✅ Заявка не отменена.",
    no_cancel_booking: "❌ Нет заявки для отмены.",
    booking_not_found_or_canceled: "❌ Заявка не найдена или уже отменена.",
    application_canceled: "❌ Ваша заявка отменена.",
    new_booking_prompt: "🔄 Для записи на новую встречу нажмите кнопку в меню.",
    unexpected_text_ignore:
      "User {id} in scene {scene}, ignoring unexpected text: {text}",
    global_error_reply:
      "❌ Произошла ошибка, пожалуйста, отправьте /start заново.",
    existing_application:
      "❌ У вас уже есть заявка (№: {id}, Статус: {status}, Заявитель: {name}). Чтобы подать новую, сначала отмените текущую.",
    no_application: "❌ У вас нет активной заявки.",
    file_not_found: "❌ Файл не найден.",
    additional_info:
      "📗 Дополнительная информация: Здесь может быть полезный текст или ссылки.", // Placeholder
    language_prompt: "🌐 Пожалуйста, выберите язык:",
    group_join: "🫂 Перейти в группу",
    application_copy: "🖨️ Получить копию заявки",
    additional_info_button: "📗 Дополнительная информация",
    visitor_reminder: "📃 Памятка для посетителей",
    colony_location_button: "🏛️ Локация колонии",
    yes: "✅ Да",
    no: "❌ Нет",
    status_approved: "одобрено",
    status_pending: "ожидает",
    change_language: "🌐 Сменить язык",
    internal_error: "❌ Внутренняя ошибка бота. Пожалуйста, попробуйте снова.",
    existing_pending:
      "⚠️ У вас есть незавершенная заявка. Чтобы создать новую, завершите или отмените текущую.",
    phone_saved: "✅ Ваш номер телефона сохранен. Примите оферту.",
    offer_prompt:
      "📜 Пожалуйста, прочитайте ПУБЛИЧНУЮ ОФЕРТУ и нажмите 'Принимаю' для принятия:",
    read_offer: "📖 Прочитать ПУБЛИЧНУЮ ОФЕРТУ",
    accept_offer: "✅ Принимаю",
    request_phone: "📲 Пожалуйста, отправьте свой номер телефона через кнопку:",
    contact_button: "🟢➡️ 📞 Отправить номер ⬅️🟢",
    phone_accepted: "✅ Номер телефона принят.",
    retry_phone:
      "📱 Отправьте номер телефона только через кнопку. Не пишите номер текстом:",
    retry_contact_button: "📞 Отправить номер",
    too_many_retries:
      "❌ Вы слишком много раз отправили неверные данные. Пожалуйста, начните заново с /start.",
    select_colony: "🏛 Пожалуйста, выберите КОЛОНИЮ:",
    colony_button: (c) => `🏛 ${c}-я колония ${c === "23" ? "МУИК" : "ЖИЭК"}`,
    select_visit_type: "⏲️ Пожалуйста, выберите тип ВСТРЕЧИ:",
    short_visit: "🔵 1-дневная",
    long_visit: "🟢 2-дневная",
    enter_full_name:
      "👤 Пожалуйста, введите ваше полное имя: (ФАМИЛИЯ ИМЯ ОТЧЕСТВО)",
    cancel_text: "❌ Отменить заявку",
    invalid_name: "❌ Пожалуйста, введите имя и фамилию в текстовом формате.",
    enter_prisoner_name:
      "👥 С кем вы хотите встретиться? Введите полное имя заключенного: (ФАМИЛИЯ ИМЯ ОТЧЕСТВО)",
    invalid_prisoner:
      "❌ Пожалуйста, введите имя заключенного в текстовом формате.",
    add_more_prompt: "➕ Хотите добавить еще родственника? (максимум 3)",
    yes_add: "Да, добавить",
    no_done: "Нет",
    max_reached: "⚠️ Максимум 3 родственника добавлено.",
    new_relative: "👤 Введите имя и фамилию нового родственника:",
    summary_title: "📋 Детали вашей заявки:",
    summary_colony: (colony) =>
      `🏛 Колония: ${colony}-я ${colony === "23" ? "МУИК" : "ЖИЭК"}`,
    summary_prisoner: (name) => `👤 Заключенный: ${name}`,
    summary_relative: (i, name) => `👥 Родственник ${i + 1}: ${name}`,
    confirm_prompt: "❓ Подтверждаете эти данные?",
    confirm_button: "✅ Подтвердить",
    cancel_button: "❌ Отменить заявку",
    booking_canceled: "❌ Запись на встречу отменена.",
    booking_saved: (position) =>
      `✅ Заявка на встречу отправлена!\n📊 Ваша очередь: ${position}`,
    queue_status: "📊 Статус очереди",
    cancel_application: (id) => `❌ Отменить заявку #${id}`,
    join_group: "🫂 Присоединитесь к группе",
    group_button: "📌 Перейти в группу",
    admin_new: (id) => `📌 Новая заявка. №: ${id}`,
    admin_applicant: (name) => `👥 Заявитель: ${name}`,
    admin_colony: (colony) =>
      `🏛 Колония: ${colony}-я ${colony === "23" ? "МУИК" : "ЖИЭК"}`,
    admin_date: (date) => `📅 Дата подачи: ${date}`,
    admin_type: (isLong) => `⏲️ Тип: ${isLong ? "2-дневная" : "1-дневная"}`,
    admin_status: "🟡 Статус: Ожидает проверки",
    error: "❌ Произошла ошибка. Пожалуйста, попробуйте позже.",
    not_found: "❌ Ошибка: Ваша заявка не найдена.",
    book_meeting: "📅 Записаться на встречу",
    payment_title: "Оплата услуги бота-свиданий",
    payment_desc: "Оплата 12500 сум за подачу заявки",
    payment_success: "✅ Оплата прошла успешно!\n✅ У Вас есть 2 (две) попытки.",
    attemptsLeft: (attempts) => `✅ У Вас осталось ${attempts} ${attempts == 2 ? "(две) " : "(одна)"} попытки.`,
    continue: "Продолжить",
    payment_not_verified: "Оплата не подтверждена.",
    payment_error: "Произошла ошибка при оплате.",
    pay_or_cancel: "Оплатите или отмените.",
    payment_canceled: "Оплата отменена. Запишитесь на встречу заново.",
    payment_already_processed: "Оплата уже обработана.",
    booking_payment_error: "❌ Произошла ошибка при оплате бронирования, Попробуйте еще раз.",
    unexpected_input: "❌ Непредвиденный ввод. Пожалуйста, следуйте инструкциям.",
  },
  uz: {
    // Uzbek Cyrillic
    greeting:
      "👋 Ассалому алайкум!\nБу платформа орқали сиз қамоқхона маҳбуслари билан учрашувга ёзилишингиз мумкин.",
    process_canceled: "❌ Жараён бекор қилинди.",
    error_occurred: "❌ Хатолик юз берди.",
    main_menu: "Асосий меню:",
    already_in_process:
      "❌ Сиз аллақачон жараёндасиз. Илтимос, жорий жараённи якунланг ёки /cancel буйруғини ишлатинг.",
    approved_status: `🎉 Ариза тасдиқланган. №: {id}\n👤 Аризачи: {name}`,
    pending_status: `📊 Сизнинг навбатингиз: {pos}`,
    queue_not_found: "❌ Навбат топилмади.",
    no_pending_application: "❌ Сизда ҳозирда кутаётган ариза йўқ.",
    approved_details: `🎉 Ариза тасдиқланган. №: {id}\n👤 Аризачи: {name}\n📅 Берилган сана: {created}\n⌚️ Келиши сана: {visit}\n🏛️ Колония: {colony}\n🟢 Ҳолат: Тасдиқланган`,
    status_unknown: "❌ Ариза ҳолати номаълум.",
    no_booking_found: "❌ Ҳозирда ариза топилмади.",
    group_join_prompt: "🫂 Тугмасини босинг:",
    group_join_button: "📌 Гуруҳга ўтиш",
    no_active_application: "❌ Сизда ҳозирда фаол ариза йўқ.",
    coordinates_not_found: "❌ Колониа координаталари топилмади.",
    colony_location: "🏛 {colony}-сон ЖИЭК локацияси",
    cancel_confirm: "❓ Аризани бекор қилмоқчимисиз?",
    cancel_no: "✅ Ариза бекор қилинмади.",
    no_cancel_booking: "❌ Ҳозир бекор қилиш учун ариза топилмади.",
    booking_not_found_or_canceled:
      "❌ Ариза топилмади ёки аллақачон бекор қилинган.",
    application_canceled: "❌ Сизнинг аризангиз бекор қилинди.",
    new_booking_prompt:
      "🔄 Янги учрашувга ёзилиш учун менюдаги тугмани босинг.",
    unexpected_text_ignore:
      "User {id} in scene {scene}, ignoring unexpected text: {text}",
    global_error_reply:
      "❌ Хатолик юз берди, илтимос, /start буйруғини қайта юборинг.",
    existing_application:
      "❌ Сизда аллақачон ариза мавжуд (№: {id}, Ҳолат: {status}, Аризачи: {name}). Янги ариза юбориш учун аввал жорий аризани бекор қилинг.",
    no_application: "❌ Сизда ҳозирда кутаётган ариза йўқ.",
    file_not_found: "❌ Файл топилмади.",
    additional_info:
      "📗 Қўшимча маълумот: Бу ерда фойдали матн ёки ҳаволалар бўлиши мумкин.", // Placeholder
    language_prompt: "🌐 Илтимос, тилни танланг:",
    group_join: "🫂 Гуруҳга ўтиш",
    application_copy: "🖨️ Ариза нусхасини олиш",
    additional_info_button: "📗 Қўшимча маълумот",
    visitor_reminder: "📃 Ташриф буюрувчилар учун эслатма",
    colony_location_button: "🏛️ Колониа локацияси",
    yes: "✅ Ҳа",
    no: "❌ Йўқ",
    status_approved: "тасдиқланган",
    status_pending: "кутмоқда",
    change_language: "🌐 Тилни ўзгартириш",
    internal_error: "❌ Ботнинг ички хатоси. Илтимос, қайта уриниб кўринг.",
    existing_pending:
      "⚠️ Сизда ҳали тугалланмаган ариза мавжуд. Янги ариза яратиш учун уни якунланг ёки бекор қилинг.",
    phone_saved: "✅ Телефон рақамингиз сақланган. Оферта қабул қилинг.",
    offer_prompt:
      "📜 Илтимос, ОМАВИЙ ОФЕРТАНИ ўқинг ва қабул қилиш учун 'Қабул қиламан' тугмасини босинг:",
    read_offer: "📖 ОМАВИЙ ОФЕРТАНИ ўқиш",
    accept_offer: "✅ Қабул қиламан",
    request_phone: "📲 Илтимос, телефон рақамингизни тугма орқали юборинг:",
    contact_button: "🟢➡️ 📞 Рақамни юбориш ⬅️🟢",
    phone_accepted: "✅ Телефон рақамингиз қабул қилинди.",
    retry_phone:
      "📱 Телефон рақамингизни фақат тугма орқали юборинг. Рақамни матн сифатида ёзманг:",
    retry_contact_button: "📞 Рақамни юбориш",
    too_many_retries:
      "❌ Сиз кўп марта нотўғри маълумот юбордингиз. Илтимос, /start буйруғи билан қайтадан бошланг.",
    select_colony: "🏛 Илтимос, КОЛОНИЯНИ танланг:",
    colony_button: (c) => `🏛 ${c}-сон колония ${c === "23" ? "МУИК" : "ЖИЭК"}`,
    select_visit_type: "⏲️ Илтимос, УЧРАШУВ турини танланг:",
    short_visit: "🔵 1-кунлик",
    long_visit: "🟢 2-кунлик",
    enter_full_name:
      "👤 Илтимос, тўлиқ исмингизни киритинг: (ФАМИЛИЯ ИСМ ШАРИФИ)",
    cancel_text: "❌ Аризани бекор қилиш",
    invalid_name: "❌ Илтимос, исм ва фамилияни матн шаклида юборинг.",
    enter_prisoner_name:
      "👥 Сиз ким билан учрашмоқчисиз? Маҳбуснинг тўлиқ исмини киритинг: (ФАМИЛИЯ ИСМ ШАРИФИ)",
    invalid_prisoner: "❌ Илтимос, маҳбуснинг исмини матн шаклида юборинг.",
    add_more_prompt: "➕ Яна қариндош қўшишни хоҳлайсизми? (максимал 3 та)",
    yes_add: "Ҳа, қўшаман",
    no_done: "Йўқ",
    max_reached: "⚠️ Максимал 3 та қариндош қўшилди.",
    new_relative: "👤 Янги қариндошнинг исми ва фамилиясини киритинг:",
    summary_title: "📋 Аризангиз тафсилотлари:",
    summary_colony: (colony) =>
      `🏛 Колониа: ${colony}-сон ${colony === "23" ? "МУИК" : "ЖИЭК"}`,
    summary_prisoner: (name) => `👤 Маҳбус: ${name}`,
    summary_relative: (i, name) => `👥 Қариндош ${i + 1}: ${name}`,
    confirm_prompt: "❓ Ушбу маълумотларни тасдиқлайсизми?",
    confirm_button: "✅ Тасдиқлаш",
    cancel_button: "❌ Аризани бекор қилиш",
    booking_canceled: "❌ Учрашув ёзуви бекор қилинди.",
    booking_saved: (position) =>
      `✅ Учрашув аризани бериш учун юборилди!\n📊 Сизнинг навбатингиз: ${position}`,
    queue_status: "📊 Навбат ҳолати",
    cancel_application: (id) => `❌ Аризани бекор қилиш #${id}`,
    join_group: "🫂 Гуруҳга қўшинг",
    group_button: "📌 Гуруҳга ўтиш",
    admin_new: (id) => `📌 Янги ариза. №: ${id}`,
    admin_applicant: (name) => `👥 Аризачи: ${name}`,
    admin_colony: (colony) =>
      `🏛 Колониа: ${colony}-сон ${colony === "23" ? "МУИК" : "ЖИЭК"}`,
    admin_date: (date) => `📅 Берилган сана: ${date}`,
    admin_type: (isLong) => `⏲️ Тури: ${isLong ? "2-кунлик" : "1-кунлик"}`,
    admin_status: "🟡 Ҳолат: Текширувни кутиш",
    error: "❌ Хатолик юз берди. Илтимос, кейинроқ уриниб кўринг.",
    not_found: "❌ Хатолик: Аризангиз топилмади.",
    book_meeting: "📅 Учрашувга ёзилиш",
    payment_title: "Учрашув-бот хизмати тўлов",
    payment_desc: "Аризани топшириш учун 12500 сўм тўлов",
    payment_success: "✅ Тўлов амалга ошди!\n✅ Сизда 2 (иккита) уриниш бор.",
    attemptsLeft: (attempts) => `✅ Сизда ${attempts} ${attempts == 2 ? "(иккита) " : "(битта)"} уриниш қолди.`,
    continue: "Давом эттириш",
    payment_not_verified: "Тўлов тасдиқланмади.",
    payment_error: "Тўловда хатолик юз берди.",   
    pay_or_cancel: "Тўловни амалга оширинг ёки бекор қилинг.",
    payment_canceled: "Тўлов бекор қилинди. Учрашувга ёзилинг.",
    payment_already_processed: "Тўлов аллақачон қайта ишланди.",
    booking_payment_error: "❌ Брон қилиш тўловида хатолик юз берди, Қайта уриниб кўринг.",
    unexpected_input: "❌ Нотўғри киритиш. Илтимос, кўрсатмаларга риоя қилинг.",
  },
  uzl: {
    // Uzbek Latin (original)
    greeting:
      "👋 Assalomu alaykum!\nBu platforma orqali siz qamoqxona mahbuslari bilan uchrashuvga yozilishingiz mumkin.",
    process_canceled: "❌ Jarayon bekor qilindi.",
    error_occurred: "❌ Xatolik yuz berdi.",
    main_menu: "Asosiy menu:",
    already_in_process:
      "❌ Siz allaqachon jarayondasiz. Iltimos, joriy jarayonni yakunlang yoki /cancel buyrug‘ini ishlating.",
    approved_status: `🎉 Ariza tasdiqlangan. №: {id}\n👤 Arizachi: {name}`,
    pending_status: `📊 Sizning navbatingiz: {pos}`,
    queue_not_found: "❌ Navbat topilmadi.",
    no_pending_application: "❌ Sizda hozirda kutayotgan ariza yo‘q.",
    approved_details: `🎉 Ariza tasdiqlangan. №: {id}\n👤 Arizachi: {name}\n📅 Berilgan sana: {created}\n⌚️ Kelishi sana: {visit}\n🏛️ Koloniya: {colony}\n🟢 Holat: Tasdiqlangan`,
    status_unknown: "❌ Ariza holati noma'lum.",
    no_booking_found: "❌ Hozirda ariza topilmadi.",
    group_join_prompt: "🫂 Tugmasini bosing:",
    group_join_button: "📌 Grupaga otish",
    no_active_application: "❌ Sizda hozirda faol ariza yo‘q.",
    coordinates_not_found: "❌ Koloniya koordinatalari topilmadi.",
    colony_location: "🏛 {colony}-son JIEK lokatsiyasi",
    cancel_confirm: "❓ Arizani bekor qilmoqchimisiz?",
    cancel_no: "✅ Ariza bekor qilinmadi.",
    no_cancel_booking: "❌ Hozir bekor qilish uchun ariza topilmadi.",
    booking_not_found_or_canceled:
      "❌ Ariza topilmadi yoki allaqachon bekor qilingan.",
    application_canceled: "❌ Sizning arizangiz bekor qilindi.",
    new_booking_prompt:
      "🔄 Yangi uchrashuvga yozilish uchun menyudagi tugmani bosing.",
    unexpected_text_ignore:
      "User {id} in scene {scene}, ignoring unexpected text: {text}",
    global_error_reply:
      "❌ Xatolik yuz berdi, iltimos, /start buyrug‘ini qayta yuboring.",
    existing_application:
      "❌ Sizda allaqachon ariza mavjud (№: {id}, Holat: {status}, Arizachi: {name}). Yangi ariza yuborish uchun avval joriy arizani bekor qiling.",
    booking_canceled: "❌ Uchrashuv yozuvi bekor qilindi.",
    no_application: "❌ Sizda hozirda kutayotgan ariza yo‘q.",
    file_not_found: "❌ Fayl topilmadi.",
    additional_info:
      "📗 Qo‘shimcha ma’lumot: Bu yerda foydali matn yoki havolalar bo‘lishi mumkin.", // Placeholder
    language_prompt: "🌐 Iltimos, tilni tanlang:",
    group_join: "🫂 Grupaga otish",
    application_copy: "🖨️ Ariza nusxasini olish",
    additional_info_button: "📗 Qo‘shimcha ma’lumot",
    visitor_reminder: "📃 Tashrif buyuruvchilar uchun eslatma",
    colony_location_button: "🏛️ Koloniya lokatsiyasi",
    yes: "✅ Ha",
    no: "❌ Yo‘q",
    status_approved: "tasdiqlangan",
    status_pending: "kutmoqda",
    change_language: "🌐 Tilni o‘zgartirish",
    internal_error: "❌ Botning ichki xatosi. Iltimos, qayta urinib ko‘ring.",
    existing_pending:
      "⚠️ Sizda hali tugallanmagan ariza mavjud. Yangi ariza yaratish uchun uni yakunlang yoki bekor qiling.",
    phone_saved: "✅ Telefon raqamingiz saqlangan. Ofertani qabul qiling.",
    offer_prompt:
      "📜 Iltimos, OMAVIY OFERTANI o‘qing va qabul qilish uchun 'Qabul qilaman' tugmasini bosing:",
    read_offer: "📖 OMAVIY OFERTANI o‘qish",
    accept_offer: "✅ Qabul qilaman",
    request_phone: "📲 Iltimos, telefon raqamingizni tugma orqali yuboring:",
    contact_button: "🟢➡️ 📞 Raqamni yuborish ⬅️🟢",
    phone_accepted: "✅ Telefon raqamingiz qabul qilindi.",
    retry_phone:
      "📱 Telefon raqamingizni faqat tugma orqali yuboring. Raqamni matn sifatida yozmang:",
    retry_contact_button: "📞 Raqamni yuborish",
    too_many_retries:
      "❌ Siz ko‘p marta noto‘g‘ri ma’lumot yubordingiz. Iltimos, /start buyrug‘i bilan qaytadan boshlang.",
    select_colony: "🏛 Iltimos, KOLONIYANI tanlang:",
    colony_button: (c) => `🏛 ${c}-son ${c === "23" ? "MUIK" : "JIEK"}`,
    select_visit_type: "⏲️ Iltimos, UCHRASHUV turini tanlang:",
    short_visit: "🔵 1-kunlik",
    long_visit: "🟢 2-kunlik",
    enter_full_name:
      "👤 Iltimos, to‘liq ismingizni kiriting: (FAMILIYA ISM SHARIFI)",
    cancel_text: "❌ Bekor qilish ariza",
    invalid_name: "❌ Iltimos, ism va familiyani matn shaklida yuboring.",
    enter_prisoner_name:
      "👥 Siz kim bilan uchrashmoqchisiz? Mahbusning to‘liq ismini kiriting: (FAMILIYA ISM SHARIFI)",
    invalid_prisoner: "❌ Iltimos, mahbusning ismini matn shaklida yuboring.",
    add_more_prompt:
      "➕ Yana qarindosh qo‘shishni xohlaysizmi? (maksimal 3 ta)",
    yes_add: "Ha, qo‘shaman",
    no_done: "Yo‘q",
    max_reached: "⚠️ Maksimal 3 ta qarindosh qo‘shildi.",
    new_relative: "👤 Yangi qarindoshning ismi va familiyasini kiriting:",
    summary_title: "📋 Arizangiz tafsilotlari:",
    summary_colony: (colony) =>
      `🏛 Koloniya: ${colony}-son ${colony === "23" ? "MUIK" : "JIEK"}`,
    summary_prisoner: (name) => `👤 Mahbus: ${name}`,
    summary_relative: (i, name) => `👥 Qarindosh ${i + 1}: ${name}`,
    confirm_prompt: "❓ Ushbu ma’lumotlarni tasdiqlaysizmi?",
    confirm_button: "✅ Tasdiqlash",
    cancel_button: "❌ Bekor qilish ariza",
    booking_saved: (position) =>
      `✅ Uchrashuv arizani berish uchun yuborildi!\n📊 Sizning navbatingiz: ${position}`,
    queue_status: "📊 Navbat holati",
    cancel_application: (id) => `❌ Arizani bekor qilish #${id}`,
    join_group: "🫂 Grupaga qo'shing",
    group_button: "📌 Grupaga otish",
    admin_new: (id) => `📌 Yangi ariza. №: ${id}`,
    admin_applicant: (name) => `👥 Arizachi: ${name}`,
    admin_colony: (colony) =>
      `🏛 Koloniya: ${colony}-son ${colony === "23" ? "MUIK" : "JIEK"}`,
    admin_date: (date) => `📅 Berilgan sana: ${date}`,
    admin_type: (isLong) => `⏲️ Turi: ${isLong ? "2-kunlik" : "1-kunlik"}`,
    admin_status: "🟡 Holat: Tekshiruvni kutish",
    error: "❌ Xatolik yuz berdi. Iltimos, keyinroq urinib ko‘ring.",
    not_found: "❌ Xatolik: Arizangiz topilmadi.",
    book_meeting: "📅 Uchrashuvga yozilish",
    payment_title: "Uchrashuv-bot xizmati to'lov",
    payment_desc: "Arizani topshirish uchun 12500 so'm to'lov",
    payment_success: "✅ To'lov amalga oshdi!\n✅ Sizda 2 (ikkita) urinish bor.",
    attemptsLeft: (attempts) => `✅ Sizda ${attempts} ${attempts == 2 ? "(ikkita) " : "(bitta)"} urinish qoldi.`,
    continue: "Davom ettirish",
    payment_not_verified: "To'lov tasdiqlanmadi.",
    payment_error: "To'lovda xatolik yuz berdi.",
    pay_or_cancel: "To'lovni amalga oshiring yoki bekor qiling.",
    payment_canceled: "To'lov bekor qilindi. Uchrashuvga yoziling.",
    payment_already_processed: "To'lov allaqachon qayta ishlandi.",
    booking_payment_error: "❌ Bron qilish to‘lovida xatolik yuz berdi, Qayta urinib ko‘ring.",
    unexpected_input: "❌ Noto‘g‘ri kiritish. Iltimos, ko‘rsatmalarga rioya qiling.",
  },
};

module.exports = texts;